/*
  Drops all db's since some are old.
*/
DROP TABLE IF EXISTS dbapplicantscreenings;
DROP TABLE IF EXISTS dbbehavior;
DROP TABLE IF EXISTS dbdates;
DROP TABLE IF EXISTS dblog;
DROP TABLE IF EXISTS dbmasterschedule;
DROP TABLE IF EXISTS dbpersons;
DROP TABLE IF EXISTS dbscl;
DROP TABLE IF EXISTS dbshifts;
DROP TABLE IF EXISTS dbweeks;
DROP TABLE IF EXISTS notesDB;
DROP TABLE IF EXISTS archivePersonDB;
DROP TABLE IF EXISTS archiveHorseDB;
DROP TABLE IF EXISTS trainerToHorseDB;
DROP TABLE IF EXISTS horseToBehaviorDB;
DROP TABLE IF EXISTS personDB;
DROP TABLE IF EXISTS trainerDB;
DROP TABLE IF EXISTS behaviorDB;
DROP TABLE IF EXISTS horseDB;
